# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empowerment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('the_country', models.CharField(max_length=50)),
                ('description_product', models.TextField()),
            ],
        ),
    ]
