# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empowerment', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='the_country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='first_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='last_name',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_product',
            new_name='Product_Description',
        ),
        migrations.AddField(
            model_name='product',
            name='Price_In_Dollars',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
