# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empowerment', '0003_auto_20170802_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Price_In_Dollars',
            new_name='Price_in_Dollars',
        ),
    ]
