# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empowerment', '0004_auto_20170802_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
